export default (THEME = {
  AUTH_BUTTON_COLOR: '#20B2AA',
  AUTH_ERROR_INPUT_BACKGROUND_COLOR: '#E9967A',
  AUTH_ERROR_INPUT_BORDER_COLOR: 'red',
  AUTH_ERROR_TEXT_COLOR: 'red',
  AUTH_INPUT_BORDER_COLOR: 'black',
  AUTH_MAIN_BACKGROUND_COLOR: 'white',
  TEXT_COLOR: 'black',
  FONT_FAMILY: 'Roboto-Regular',
  FONT_SIZE: 14,
});
